# Parametri connessione
source=localhost:3306

# Parametri connessione DB applicazione
connection_parameters=?serverTimezone=UTC&useSSL=true&requireSSL=true

# Utenza DB App
schema_name=sna_grandolfo
user_db=sna_user
password_db=PasswordSicura123!

# Utenza DB Auth
schema_auth_name=sna_auth_grandolfo
user_auth_db=sna_auth
password_auth_db=PasswordSicurissima123!

# Path di upload per i file
upload_dir=C:/uploads/sna_grandolfo/