registerUserQuery=INSERT INTO users (email, password) VALUES (?, ?)

insertFileQuery=INSERT INTO files (name, unique_name, category, author_upload_id) VALUES (?, ?, ?, (SELECT id FROM users WHERE email = ?))

loginUserQuery=SELECT * FROM users WHERE email=? AND password=?

selectAllProposteQuery=SELECT f.id, f.name, f.data_upload, u.email FROM files f JOIN users u ON f.author_upload_id = u.id WHERE f.category = 2 ORDER BY f.data_upload DESC