# --- Query per la Registrazione ---
insertAuthUserQuery=INSERT INTO users (password, salt) VALUES (?, ?)
insertAppUserQuery=INSERT INTO users (id, email) VALUES (?, ?)

# --- Query per il Login ---
selectAppUserIdQuery=SELECT id FROM users WHERE email = ?
selectAuthUserQuery=SELECT password, salt FROM users WHERE id = ?

# Altre query
insertFileQuery=INSERT INTO files (name, unique_name, category, author_upload_id) VALUES (?, ?, ?, (SELECT id FROM users WHERE email = ?))
selectAllProposteQuery=SELECT f.id, f.name, f.data_upload, u.email FROM files f JOIN users u ON f.author_upload_id = u.id WHERE f.category = 2 ORDER BY f.data_upload DESC
selectFileNameByIdQuery=SELECT name, unique_name FROM files WHERE id = ?