registerUserQuery=INSERT INTO users (email, password) VALUES (?, ?)

insertFileQuery=INSERT INTO files (name, category, author_upload_id) VALUES (?, ?, ?)

loginUserQuery=SELECT * FROM users WHERE email=? AND password=?